#### **Métodos Numéricos II, 2025** <font size=4 color='gray'>Alan Reyes-Figueroa</font>
# <center> **Eliminación Gaussiana y Factoración LU** </center>

In [1]:
import numpy as np
from scipy import linalg as lg

## Eliminación Gaussiana

In [2]:
# Algoritmo de eliminación gaussiana (o factoración LU), en el caso más simple
def gaussianSimple(A):
    ''' Finds the gaussian reduction (U) or the LU factorization of a matrix A.
        Inputs:  A = matrix to reduce, as numpy array of shape (m,n).
        Outputs: L = triangular inferior matrix of row reductions, as numpy array of shape (m,m).
                 U = gaussian reduced matrix in row echelon form, as numpy array of shape (m,n).
    '''
    m, n = A.shape
    U = A.copy()
    L = np.eye(m)

    for k in range(0, n-1):            # iteration over columns
        for j in range(k+1, m):        # iteration over rows after k
            if (U[k,k] != 0):
                L[j,k] = U[j,k] / U[k,k]
                U[j,k:n] = U[j,k:n] - L[j,k]*U[k,k:n]
            else:
                raise Exception('A has no LU factorization')
    return L, U

In [3]:
A = np.array([[8,7,9,5], [4,3,3,1], [2.,1,1,0], [6,7,9,8]])
print(A)

[[8. 7. 9. 5.]
 [4. 3. 3. 1.]
 [2. 1. 1. 0.]
 [6. 7. 9. 8.]]


In [4]:
# descomposición LU
L, U = gaussianSimple(A)

In [5]:
print(L, end='\n\n')

print(U)

[[ 1.    0.    0.    0.  ]
 [ 0.5   1.    0.    0.  ]
 [ 0.25  1.5   1.    0.  ]
 [ 0.75 -3.5  -3.    1.  ]]

[[ 8.   7.   9.   5. ]
 [ 0.  -0.5 -1.5 -1.5]
 [ 0.   0.   1.   1. ]
 [ 0.   0.   0.   2. ]]


In [6]:
L @ U

array([[8., 7., 9., 5.],
       [4., 3., 3., 1.],
       [2., 1., 1., 0.],
       [6., 7., 9., 8.]])

In [7]:
B = np.array([[1,3,2,5], [2,6,3,1], [2.,6,1,0], [-3,-9,7,8]])
print(B)

[[ 1.  3.  2.  5.]
 [ 2.  6.  3.  1.]
 [ 2.  6.  1.  0.]
 [-3. -9.  7.  8.]]


In [8]:
L, U = gaussianSimple(B)

Exception: A has no LU factorization

In [9]:
C = np.array([[1,3,2,5], [2,6,3,1], [2.,8,1,0], [-3,-9,7,8]])
print(C)

[[ 1.  3.  2.  5.]
 [ 2.  6.  3.  1.]
 [ 2.  8.  1.  0.]
 [-3. -9.  7.  8.]]


In [10]:
L, U = gaussianSimple(C)

Exception: A has no LU factorization

In [11]:
# non square matrix A
D = np.array([[1.,5,3,2,4], [2,2,0,4,1], [2,1,8,4,2], [3,3,1,4,0]])
D

array([[1., 5., 3., 2., 4.],
       [2., 2., 0., 4., 1.],
       [2., 1., 8., 4., 2.],
       [3., 3., 1., 4., 0.]])

In [12]:
L, U = gaussianSimple(D)

In [13]:
print(L, end='\n\n')
print(U)

[[1.         0.         0.         0.        ]
 [2.         1.         0.         0.        ]
 [2.         1.125      1.         0.        ]
 [3.         1.5        0.11428571 1.        ]]

[[ 1.          5.          3.          2.          4.        ]
 [ 0.         -8.         -6.          0.         -7.        ]
 [ 0.          0.          8.75        0.          1.875     ]
 [ 0.          0.          0.         -2.         -1.71428571]]


In [14]:
L @ U

array([[1., 5., 3., 2., 4.],
       [2., 2., 0., 4., 1.],
       [2., 1., 8., 4., 2.],
       [3., 3., 1., 4., 0.]])