## <font size=4> *Métodos Numéricos II*, 2025 - </font> <font size=3 color='gray'> Alan Reyes-Figueroa </font>
# <center> <font size=8> **Descomposición SVD** </font> </center>

In [1]:
import numpy as np
from scipy import linalg as lg

# Descomposición SVD

In [2]:
A = np.array([[2.,0,0], [0,2,0], [0,0,2]])
B = np.array([[2.,1,0], [0,2,1], [0,0,2]])
C = np.array([[2.,0,1], [0,3,0], [0,0,1]])
D = np.array([[1.,1,0], [0,1,1], [1,0,1]])

print(A, end='\n\n')
print(B, end='\n\n')
print(C)

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]

[[2. 1. 0.]
 [0. 2. 1.]
 [0. 0. 2.]]

[[2. 0. 1.]
 [0. 3. 0.]
 [0. 0. 1.]]


In [3]:
# Descomposición SVD:  C = USV^T

U, S, V = lg.svd(B)

In [4]:
print(U, end='\n\n')
print(np.diag(S), end='\n\n')
print(V)                          # Aquí V les guarda la V^T

[[ 0.55480803 -0.71709346  0.42185901]
 [ 0.72851788  0.17384567 -0.66260047]
 [ 0.4018081   0.67494789  0.61886638]]

[[2.76155718 0.         0.        ]
 [0.         2.12488542 0.        ]
 [0.         0.         1.36332824]]

[[ 0.4018081   0.72851788  0.55480803]
 [-0.67494789 -0.17384567  0.71709346]
 [ 0.61886638 -0.66260047  0.42185901]]


In [5]:
recB = U @ np.diag(S) @ V
recB

array([[ 2.00000000e+00,  1.00000000e+00,  4.54048481e-16],
       [-5.08218126e-17,  2.00000000e+00,  1.00000000e+00],
       [ 3.23801469e-16,  2.01524079e-16,  2.00000000e+00]])

In [6]:
np.round(recB, 4)

array([[ 2.,  1.,  0.],
       [-0.,  2.,  1.],
       [ 0.,  0.,  2.]])

In [7]:
X = np.array([[5, 0, 2], [7, 3, 5], [-4, 1, 0], [3, -1, -2]])
X

array([[ 5,  0,  2],
       [ 7,  3,  5],
       [-4,  1,  0],
       [ 3, -1, -2]])

In [8]:
U, S, V = lg.svd(X)

In [9]:
U

array([[-0.48100974, -0.18479081, -0.57428191,  0.63614643],
       [-0.80821037,  0.43457194,  0.36627893, -0.15421732],
       [ 0.30607206,  0.51110555,  0.36926711,  0.71325508],
       [-0.14746367, -0.71817178,  0.63220395,  0.25060314]])

In [10]:
S

array([10.98677289,  4.60882821,  1.02446277])

In [11]:
S = np.hstack([S, np.array([0])])
S

array([10.98677289,  4.60882821,  1.02446277,  0.        ])

In [12]:
np.diag(S)[:,:-1]

array([[10.98677289,  0.        ,  0.        ],
       [ 0.        ,  4.60882821,  0.        ],
       [ 0.        ,  0.        ,  1.02446277],
       [ 0.        ,  0.        ,  0.        ]])

In [13]:
V

array([[-0.8855376 , -0.17940622, -0.42852838],
       [-0.45150044,  0.54959591,  0.70291655],
       [ 0.10940985,  0.81593979, -0.56768983]])

In [14]:
U @ np.diag(S)[:,:-1] @ V

array([[ 5.00000000e+00,  5.25737863e-16,  2.00000000e+00],
       [ 7.00000000e+00,  3.00000000e+00,  5.00000000e+00],
       [-4.00000000e+00,  1.00000000e+00,  2.18430055e-15],
       [ 3.00000000e+00, -1.00000000e+00, -2.00000000e+00]])

In [15]:
U, S, V = lg.svd(X, full_matrices=False)

In [16]:
U

array([[-0.48100974, -0.18479081, -0.57428191],
       [-0.80821037,  0.43457194,  0.36627893],
       [ 0.30607206,  0.51110555,  0.36926711],
       [-0.14746367, -0.71817178,  0.63220395]])

In [17]:
S

array([10.98677289,  4.60882821,  1.02446277])

In [18]:
V

array([[-0.8855376 , -0.17940622, -0.42852838],
       [-0.45150044,  0.54959591,  0.70291655],
       [ 0.10940985,  0.81593979, -0.56768983]])

## Ejemplo en clase:

In [19]:
D

array([[1., 1., 0.],
       [0., 1., 1.],
       [1., 0., 1.]])

In [20]:
U, S, V = lg.svd(D)

In [21]:
print(U)

[[-5.77350269e-01  4.08248290e-01 -7.07106781e-01]
 [-5.77350269e-01 -8.16496581e-01 -1.25371672e-16]
 [-5.77350269e-01  4.08248290e-01  7.07106781e-01]]


In [22]:
print(S)

[2. 1. 1.]


In [23]:
print(V)

[[-0.57735027 -0.57735027 -0.57735027]
 [ 0.81649658 -0.40824829 -0.40824829]
 [ 0.         -0.70710678  0.70710678]]


In [24]:
print(np.round(U @ np.diag(S) @ V))

[[ 1.  1. -0.]
 [ 0.  1.  1.]
 [ 1. -0.  1.]]


## Descomposición de Schur

In [25]:
# Descomposición de Schur:  C = QTQ^T

T, Q = lg.schur(C)

In [26]:
print(Q, end='\n\n')
print(T)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[2. 0. 1.]
 [0. 3. 0.]
 [0. 0. 1.]]


In [27]:
recC = Q @ T @ Q.T
recC

array([[2., 0., 1.],
       [0., 3., 0.],
       [0., 0., 1.]])

In [28]:
E = np.array([[2.,0,0], [0,3,0], [1,0,1]])
E

array([[2., 0., 0.],
       [0., 3., 0.],
       [1., 0., 1.]])

In [29]:
T, Q = lg.schur(E)

In [30]:
print(Q, end='\n\n')
print(T)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

[[1. 1. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


In [31]:
recE = Q @ T @ Q.T
recE

array([[2., 0., 0.],
       [0., 3., 0.],
       [1., 0., 1.]])